### ISSUE TITLE
doc: broken links in labs

### ISSUE THREAD

**Issue by fanghuaqi** [foss-for-synopsys-dwc-arc-processors/arc_labs#26]
- labs/level1/lab2.rst:23: [broken] http://embarc.org/embar: 404 Client Error: Not Found for url: http://embarc.org/embar
- labs/level2/dsp_lab2_fxapi.rst:163: [broken] https://github.com/foss-for-synopsys-dwc-arc-processors/embarc_osp/tree/feature/iotdk/board/iotdk/configs/10/tcf/arcem9d.tcf: 404 Client Error: Not Found for url: https://github.com/foss-for-synopsys-dwc-arc-processors/embarc_osp/tree/feature/iotdk/board/iotdk/configs/10/tcf/arcem9d.tcf

**Comment by YuguoWH** [comment]
fix in 8890b84ab86f7139cd5d18f86d42c4df63ef67dc
